#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fpath+=$HOME/.zsh/pure

autoload -U promptinit; promptinit
zstyle :prompt:pure:path color cyan
prompt pure

export EDITOR='nvim'
export VISUAL="$EDITOR"

export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1

export PATH=$PATH:/usr/local/go/bin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
export PATH="${PATH}:/mnt/c/Program Files/Oracle/VirtualBox"
[ -f "/home/jacob/.ghcup/env" ] && source "/home/jacob/.ghcup/env" # ghcup-env

LS_COLORS="ow=01;36;40" && export LS_COLORS

alias gs="git status"
alias nw="cd ~/vimwiki && nvim index.md -c VenterToggle"
alias lg='lazygit'
alias wthr='curl wttr.in'
alias config="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
